### PR TITLE
Show tree details + Use onsenui framework

### PR DESCRIPTION
**Pull request by RobinCsl**
Hi everyone,
This is my first try at making a pull request on github, I hope I am doing this correctly. 
Anyway, I've managed to: 
- get some scaffolding of onsen-ui,
- get API calls to the server, retrieve the data and display it in the onsen-ui view.

To be able to view it, you need to insert some dummy data in the tree table in the DB and use the filename as "img/tree1.jpg".

To be done:
- add error message in case the HTTP request fails,
- add the passing of the tree id from the map view.

### CODE REVIEW

**Comment by chill117** [comment]
Can you remove the dependencies from git? These include all the files in `node_modules` and `app/www/node_modules`.

**Comment by RobinCsl** [comment]
Is it okay now?

**Comment by chill117** [comment]
Great! Thanks :)

I'll try to run it on my machine.

**Comment by chill117** [comment]
I rebased your branch with upstream/master so that I could add the stuff with grunt/copy. I also added the onsenui and vue dependencies to the package.json in the app directory.

Things appears to be working as you had it. How far do you want to go with this pull request?

**Comment by RobinCsl** [comment]
I have added a few commits taking care of the two items in the to-do list I had written above. Could you please review them? @chill117 
Thank you :-)

**Pull request merged**
