### PR TITLE
Changed map marker for trees

### PR DESCRIPTION
**Pull request by fidraj**

### CODE REVIEW

**Comment by fidraj** [comment]
TODO: SVG icons iconfinder.com

**Comment by fidraj** [comment]
Tree icon looks like this now: https://www.dropbox.com/s/sg4vd9qzbrlnfd8/Screenshot%202017-06-05%2013.56.56.png?dl=0

**Comment by chill117** [comment]
Hmmm... It doesn't look good. Maybe we could try this:
https://github.com/lvoogdt/Leaflet.awesome-markers

The above leaflet plugin with font-awesome (built with minimal icons, if possible) so that we can easily render visually different markers (with shadows, different background color or icon).

**Comment by fidraj** [comment]
Ok, will do

**Comment by chill117** [comment]
@fidraj You should remove your last commit (the merge from master) and do a rebase instead.

**Comment by fidraj** [comment]
I won't be able to continue attending our classes. Sorry.

**Pull request closed without merging**
